# Generated by Django 2.2.4 on 2009-03-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachings',
            name='contact',
            field=models.CharField(default=91, max_length=15),
            preserve_default=False,
        ),
    ]
